project:
  type: book
  output-dir: ../docs

book:
  title: "Notes de cours - MAT8186"
  author: "Cedric Beaulac"
  date: "2026-08-01"
  chapters:
    - index.qmd
    - survol.qmd
    - Rproject.qmd
    - Git.qmd
    - Package.qmd
    - references.qmd

bibliography: references.bib

execute:
  enabled: false

format:
  html:
    theme: spacelab
  pdf:
    documentclass: scrreprt

editor: visual

